name: pc-mb-vbox
version: '16.04-0.9'
type: gadget
summary: PC gadget for generic devices
description: |
    Generic PC fork of AMD64 gadget. Simply adds a serial-port for VBOX.
grade: stable
confinement: strict
icon: icon.png

parts:
  grub-prepare:
    plugin: nil
    stage-packages:
      - grub-efi-amd64-signed
      - grub-pc-bin
      - shim-signed
    prime: [ -* ]
  grub:
    source: .
    build-packages:
      - grub-common
    plugin: make
    after: [grub-prepare]

slots:
    gps:
        interface: serial-port
        usb-vendor: 0x0403
        usb-product: 0x6001
        path: /dev/serial-port-gps
